"""add cattle name field in cattle table
Revision ID: 9573a5aa3715
Revises: dc07e4da08b7
Create Date: 2025-11-18 15:46:13.296039
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9573a5aa3715'
down_revision = 'dc07e4da08b7'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cattles', sa.Column('cattle_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cattles', 'cattle_name')
    # ### end Alembic commands ###
