"""add cattle fields: weight, health_condition, purchased_date, source, photo_url

Revision ID: b4f3a2c1d9e2
Revises: 6c11b86fbdc3
Create Date: 2025-10-28 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f3a2c1d9e2'
down_revision: Union[str, Sequence[str], None] = '6c11b86fbdc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cattles', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('cattles', sa.Column('health_condition', sa.String(length=100), nullable=True))
    op.add_column('cattles', sa.Column('purchased_date', sa.DateTime(), nullable=True))
    op.add_column('cattles', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('cattles', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cattles', 'photo_url')
    op.drop_column('cattles', 'source')
    op.drop_column('cattles', 'purchased_date')
    op.drop_column('cattles', 'health_condition')
    op.drop_column('cattles', 'weight')
    # ### end Alembic commands ###
