"""added ownership transfer table
Revision ID: e0a533ddf624
Revises: 51404701bced
Create Date: 2025-12-09 01:28:56.010785
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision = 'e0a533ddf624'
down_revision = '51404701bced'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownership_transfers',
    sa.Column('otid', sa.Uuid(), nullable=False),
    sa.Column('cattle_id', sa.Uuid(), nullable=False),
    sa.Column('from_owner_id', sa.Uuid(), nullable=True),
    sa.Column('to_owner_id', sa.Uuid(), nullable=True),
    sa.Column('from_full_name', sa.String(length=120), nullable=False),
    sa.Column('from_contact_no', sa.String(length=20), nullable=True),
    sa.Column('from_aadhar_no', sa.String(length=30), nullable=True),
    sa.Column('from_inaph_id', sa.String(length=50), nullable=True),
    sa.Column('from_address', sa.String(length=300), nullable=True),
    sa.Column('to_full_name', sa.String(length=120), nullable=False),
    sa.Column('to_contact_no', sa.String(length=20), nullable=True),
    sa.Column('to_aadhar_no', sa.String(length=30), nullable=True),
    sa.Column('to_inaph_id', sa.String(length=50), nullable=True),
    sa.Column('to_address', sa.String(length=300), nullable=True),
    sa.Column('cattle_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transfer_reason', sa.String(length=255), nullable=True),
    sa.Column('other_details', sa.Text(), nullable=True),
    sa.Column('proposed_transfer_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('handover_location', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattles.cid'], ),
    sa.ForeignKeyConstraint(['from_owner_id'], ['farmers.fid'], ),
    sa.ForeignKeyConstraint(['to_owner_id'], ['farmers.fid'], ),
    sa.PrimaryKeyConstraint('otid')
    )
    op.create_index(op.f('ix_ownership_transfers_cattle_id'), 'ownership_transfers', ['cattle_id'], unique=False)
    op.create_index(op.f('ix_ownership_transfers_from_owner_id'), 'ownership_transfers', ['from_owner_id'], unique=False)
    op.create_index(op.f('ix_ownership_transfers_otid'), 'ownership_transfers', ['otid'], unique=False)
    op.create_index(op.f('ix_ownership_transfers_to_owner_id'), 'ownership_transfers', ['to_owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farmers', type_='unique')
    op.create_index(op.f('ix_farmers_inaph_id'), 'farmers', ['inaph_id'], unique=True)
    op.alter_column('farmers', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cattles', 'cattle_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cattle_complaints', 'complaint_id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_ownership_transfers_to_owner_id'), table_name='ownership_transfers')
    op.drop_index(op.f('ix_ownership_transfers_otid'), table_name='ownership_transfers')
    op.drop_index(op.f('ix_ownership_transfers_from_owner_id'), table_name='ownership_transfers')
    op.drop_index(op.f('ix_ownership_transfers_cattle_id'), table_name='ownership_transfers')
    op.drop_table('ownership_transfers')
    # ### end Alembic commands ###
