name: LifeTag Backend Deployment

on:
  push:
    branches:
      - backend
    paths:
      - 'fastapi/**'
      - 'app/**'
      - 'requirements.txt'
      - '.github/workflows/lifetag-backend-deploy.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy LifeTag to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/LifeTag
            git pull origin backend
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart lifetag
